exclude: >
  docs|
  node_modules|
  .git|
  .tox|migrations
fail_fast: true

repos:
  - repo: meta
    hooks:
      - id: identity

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-ast
      - id: check-merge-conflict
      - id: detect-private-key
        exclude: .gitlab/ci/ssh_key
      - id: mixed-line-ending
      - id: debug-statements

  - repo: https://github.com/psf/black
    rev: 21.4b1
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.9.3
    hooks:
      - id: isort

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.23.3
    hooks:
      - id: pyupgrade
        args: [--py3-plus, --py36-plus]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-pytest-style
          - flake8-implicit-str-concat
          - pep8-naming

# vim: set et ts=2 sw=2
