# Generated by Django 3.2.7 on 2021-09-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="is_remove",
            field=models.BooleanField(default=False),
        ),
    ]
